### ISSUE TITLE
Feature Request: Option for authenticating with api key

### ISSUE THREAD

**Issue by MatthewFlamm** [sdwilsh/aiotruenas-client#36]
I would like support for authenticating with a token.  There is the `auth.token` service on websocket api.

Id be willing to contribute to this.  I'm not too familiar with websocket however, so I need to take a closer look.

My idea would be to create mixin classes to provide methods for connecting via either auth method in the  `CachingMachine` class.  This would also enable other auth methods.  A separate class method like `create_from_token` could be used.

**Comment by sdwilsh** [comment]
I just updated to TrueNAS last week and was hoping to get to something like this soon, so I certainly like the idea :)

I think we can get away with just adding an auth token argument to `create` and `connect` in `CachingMachine`, and then in `connect` we do some validation to make sure either `auth_token` or `username` and `password` are passed in.  We'd also need to update `TrueNASWebSocketClientProtocol` as well.  We could either make a new base class and have `TrueNASUsernamePasswordWebSocketClientProtocol` and `TrueNASTokenWebSocketClientProtocol`, or just do the multi-arg thing.  I don't have a strong preference to be honest.

Lastly, would be to write some tests to verify things with the auth token.  We'd want to rename the two existing methods on `TestCachingMachineAuth` for testing auth, and then add two more for the token auth.

I'm more than happy to help you through this, if you want to try and tackle it.

**Comment by MatthewFlamm** [comment]
Changed this to be a feature request for api key since that is actually what I wanted.
